version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    
  app:
    build: .
    container_name: overcode-container
    depends_on: 
      - db
    volumes: 
      - .:/app
    ports: 
      - "8000:8000"
    environment:
      - DB_HOST=db