version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file:
      - ./scripts/db_actions/.env.example
      - ./scripts/db_actions/.env
    ports: "5432:5432"
    
  app:
    build: .
    depends_on: db
    volumes: .:/app
    ports: "8000:8000"
    env_file:
      - ./scripts/db_actions/.env.example 
      - ./scripts/db_actions/.env
    environment:
      - DB_HOST=db